services:
  - type: static_site
    name: apollo-green-frontend
    buildCommand: npm ci && npm run build
    publishPath: build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
